### ISSUE TITLE
RSpec cannot be found

### ISSUE THREAD

**Issue by erdebee** [dkowis/Cucumber-JVM-Ruby-Example#5]
When I run a clean pull using mvn test, the tests fail indicating that rspec library can not be found.

Doing:

root$ git pull 
root$ mvn test

Results in:

Tests in error: 
  initializationError(com.rackspace.example.stackTest): (LoadError) no such file to load -- rspec

Further inspection, checking inside gems dir and Gemfile.lock file I find rspec being there, 

GEM
  remote: http://rubygems.org/
  specs:
    diff-lcs (1.1.3)
    rspec (2.8.0)

I am running this on a MAC with Yosemite, with maven 3.2.1

**Comment by dkowis** [comment]
Sure enough, I get this on linux as well. I'll have to look into it and figure out why rspec isn't available to the Jruby....

**Comment by dkowis** [comment]
Should be fixed now.
